### ISSUE TITLE
Sub-page Nav Bar

### ISSUE THREAD

**Issue by adrollin** [Aurora-Media-Group/web-redesign#2]
When on Subpage, IE. photography.html
Select Home on Navbar and notice nothing happens. 
Select About us on Navbar and notice it goes to About us on Subpage despite the href being "index.html/about-us"
Services work, Contact has the same issue.

**Comment by umarf786** [comment]
Let me take a look at this now

**Comment by umarf786** [comment]
I have fixed the issue with selecting home and about us on navbar when on photography subpage.
This happens on the other subpages so I have fixed those too.
Contact us does not have any issues as the id of "contact" is only listed on the main page which doesn't conflict.

**Comment by umarf786** [comment]
I have noticed another issue - services dropdown links do not work at all, I have fixed these too.

**Comment by umarf786** [comment]
Pushed these into the dev branch, bug fixed

**Comment by adrollin** [comment]
Thanking you @umarf786!
